### ISSUE TITLE
Data is Hardcoded?

### ISSUE THREAD

**Issue by rehmanh** [ShahrozTanveer/covid19-pakistan#1]
Hello friend, 

I am wondering if you can leverage the API [covidAPI](https://github.com/javieraviles/covidAPI) to directly GET the COVID case data for Pakistan instead on relying on a CSV with hardcoded data in it. That way, you don't have to hardcode new data for each province each time there is an update. Let me know what you think, or if you need any help with this. Thanks!

– rehmanh

**Comment by ShahrozTanveer** [comment]
Sounds great but what if you want to get data from specific province. If you know any API which provide data by province please let me know.
Thank you.

-SharozTanveer
